@rootURL = https://localhost:7215

### Get All Genres

GET {{rootURL}}/genres
Accept: application/json

### Get All Games

GET {{rootURL}}/games
Accept: application/json

### Get Single

GET {{rootURL}}/games/2
Accept: application/json

### Create Game

POST {{rootURL}}/games
Accept: application/json
Content-Type: application/json
{
    "name": "Minecraft 2",
    "genreId": 5,
    "price": 19.99,
    "releaseDate": "2011-11-18"
}

### Update Game

PUT {{rootURL}}/games/2
Accept: application/json
Content-Type: application/json
{
    "name": "Metro 2",
    "genreId": 1,
    "price": 29.99,
    "releaseDate": "2003-11-18"
}

### Delete Game

DELETE {{rootURL}}/games/6
Accept: application/json

### 